- src/parsers/copy_row.rs
- src/parsers/row_parser.rs
- src/parsers/strategy_validator.rs
- src/parsers/transformer.rs
- test
Running on my machine with 1.2Gb db dump on my machine goes from 137s to 11s.
Main optimisations:
* Only compile regexes once
* Remove regex from `scramble`
* Optimise `scramble` to minimise memory allocations
> Make anonymiser 12x faster

- src/parsers/db_schema.rs
Before views from other schemas were being included if they had the same name as a table in the public schema
> Fix join criteria for table metadata

- src/main.rs
- src/parsers/strategy_file_reader.rs
- src/parsers/strategy_structs.rs
- Support adding missing tables with `--fix`
- Make generate-strategies work
- Add test for adding missing columns
> Make generate-strategies and check-strategies --fix work

- src/main.rs
- src/parsers/strategy_file_reader.rs
- src/parsers/strategy_structs.rs
`check-strategies --fix` and `generate-strategies` now remove redundant columns that are in the strategy file but no longer in the database.
This is the first Rust code I've written in well over a year, so it is probably very rusty ;)
> Remove redundant columns from strategy file

- .circleci/config.yml
https://app.circleci.com/pipelines/github/Multiverse-io/anonymiser/184/workflows/6494521d-86fa-48dc-bf8e-a62bd45a647c
> building releases fails as openssl is not installed

- Cargo.lock
- Cargo.toml
- src/main.rs
- src/parsers/national_insurance_number.rs
- src/parsers/row_parser.rs
- src/parsers/state.rs
- src/parsers/strategy_file.rs
- src/parsers/transformer.rs
- src/test_builders.rs
This builds off of https://github.com/Multiverse-io/anonymiser/pull/15, so that should go in first to make the changes here more clear:
Changed the default RNG source to SmallRng - a good comparison is here https://rust-random.github.io/book/guide-rngs.html, there may be even faster ones but the key point here is that we don't need a cryptographically secure implementation so its OK to use a higher performance once
Originally I changed some frequently used hashmaps to use Fnv as the hashing algorithm - It doesn't make a huge difference in this case because the benefits are only seen with very small or large keys (see graphs here https://cglab.ca/~abeinges/blah/hash-rs/), but as an example the average table name length (used as a hashmap key) is 28 bytes so not really any benefit of …
> Some optimizations

- src/file_reader.rs
- src/parsers/mod.rs
- src/parsers/rng.rs
- src/parsers/row_parser.rs
- src/parsers/transformer.rs
This PR contains various performance tweaks that yield a cumulative improvement of ~4 seconds on my dev machine. It also reduces memory usage by about 30%.
Changes:
* Replace `String` with `Cow<str>` in a number of places. This makes it possible to reuse the same allocation in cases where a column's value is unchanged.
* Slightly faster implementation of `scramble`. (This is called much more frequently than the other transformation functions, so speeding it up has a small but detectable impact on performance.)
* Avoid the (admittedly small!) cost of repeatedly initializing `SmallRng` by passing through a mutable reference to an instance of it.
* Avoid cloning `state.position` every time `row_parser::parse(...)` is called. This has quite a significant effect, as the `position` field …
> Performance tweaks

- Cargo.lock
- Cargo.toml
- src/anonymiser.rs
- src/file_reader.rs
- src/main.rs
- src/opts.rs
- src/uncompress.rs
Adds a flag to the anonymise command to compress the output using zst as part of the writing process.
Also adds a new `uncompress` command to uncompress the .zst file either to another file or stdout
```
rohan@Rohans-MacBook-Pro anonymiser % time (./target/release/anonymiser anonymise && tar -zcvf anonymised.tar.gz output.sql)   
a output.sql
( ./target/release/anonymiser anonymise && tar -zcvf anonymised.tar.gz ; )  58.59s user 2.17s system 98% cpu 1:01.74 total
rohan@Rohans-MacBook-Pro anonymiser % time ./target/release/anonymiser anonymise --compress-output --output-file anonymised.sql.zst
./target/release/anonymiser anonymise --compress-output --output-file   14.96s user 0.64s system 98% cpu 15.870 total
rohan@Rohans-MacBook-Pro anonymiser % ls -lh anonymised.*
-rw-r--r--  1 rohan …
```
> Add compress-output flag and uncompress subcommand

- src/parsers/row_parser.rs
i ran a flamegraph and one of the larger blocks is the types lookup in the row_parser..
we actually do a double hashmap lookup where we dont need to so i added a todo as a small piece if someone fancies refactoring 
zoom of the lookup bit (19% of total time)
> Remove some unused state updates, adding a todo 

- src/main.rs
- src/opts.rs
- src/parsers/strategies.rs
- src/parsers/strategy_structs.rs
- src/parsers/transformer.rs
At the moment, a compressed download of a DB we use this on is around ~1.3GB, which can take a while to download on slower connections
Part of the reason for this is the scramble transformer, which takes text like "Sample Text 123" and converts it to "kldrxv ltca 950" which is nice but also not very useful, and completely random which makes it hard to compress efficiently
By passing the flag implemented in this PR we replace it with just underscores, still retaining any whitespace, which compresses more efficiently.
Theoretically we could also remove the content completely, but we might run into issues with things like minimum lengths, or being unsure if content was actually present there.
This reduces the size quite significantly down to ~350MB, making the download faster
> Add --scramble-blank option

- .envrc
- .gitignore
- README.md
- flake.lock
- flake.nix
This addresses [sc-34401](https://app.shortcut.com/multiverse/story/34401/add-nix-flake-to-anonymiser). That ticket is part of an effort to provide a Nix flake for [Multiverse-io/platform](https://github.com/Multiverse-io/platform), which depends on anonymiser.
We could [bundle a Nix package definition into the platform source](https://github.com/Multiverse-io/platform/blob/a59bdf6d771af0c5181dc44d928c681de1c321cc/nix/anonymiser.nix), but it's more useful to include it in anonymiser directly as its developers can benefit from Nix-based dependency management.
Once Nix and direnv are installed, the main benefit of having a flake is that entering the repository directory automatically starts a subshell containing the full development dependencies (cargo, openssl, rust-analyzer, rust-clippy, …
> Add Nix flake

- README.md
- src/parsers/strategy_file.rs
- src/parsers/strategy_structs.rs
- src/parsers/transformer.rs
Heya y'all!
hope you're well, 
i had the need to be able to anonymise a field that was either a phone number OR an email (depending on a `type` variable in another column... i don't think we can couple one column to another so thought this was a better approach... 
wdyt? its pretty simple?
i also added all non General data types to the csv output as i think it makes more sense? you can always filter out the ones you dont need in the csv right?
lmk if this seems sensible!
Dan
> add an email or phone transformer

- .circleci/config.yml
- Cargo.lock
- Cargo.toml
- src/anonymiser.rs
- src/compression_type.rs
- src/file_reader.rs
- src/main.rs
- src/opts.rs
- src/uncompress.rs
add an option to use gzip compression via the command line..
this uses the higher performance c++ library
i've maintained the existing behaviour so that
`--compress-output` uses zstd
but you can now specify `--compress-output zstd` or `--compress-output gzip`
> allow gzip compression option

- src/parsers/create_row.rs
Without this, a column containing text like `CREATE TABLE` would cause a panic if it was the first column
> Ensure CREATE TABLE statement lines end with '('

- src/parsers/row_parser.rs
Heya y'all
found a bug where if a table row had whitespace at the start / end it would be removed!
we trim the row, then used the trimmed row for transformations, but actually when transforming we should use the original line, because the ACTUAL DATA can have whitespace!
we only need to trim for lines that can be indented just so we can identify them but the first non whitespace chars
> Whitespace bug

- README.md
- src/anonymiser.rs
- src/file_reader.rs
- src/fixers/db_mismatch.rs
- src/parsers/copy_row.rs
- src/parsers/row_parser.rs
- src/parsers/state.rs
- src/parsers/strategies.rs
- src/parsers/strategy_errors.rs
- src/parsers/strategy_file.rs
- src/parsers/strategy_structs.rs
- src/parsers/transformer.rs
- src/test_builders.rs
- test_files/dump_file.sql
- test_files/strategy.json
Adds an option to truncate a table!
The intent here is that for some tables (e.g. oban_jobs in our situation) we don't want any of the data from that table in our anonymised dump because its large and / or irrelevant for our purposes. The table is still created, with the same shape and config, but there is no row data in it
In the case of truncation. defining a list of columns felt a bit unnecessary as you're dropping all the data so transformers for each column don't make sense.
In order to achieve that, this pr adds a wrapper around the transformers, called `CurrentTableTransforms` which carries either the list of columns or the truncate action
Setting up the data structure occurs [here](https://github.com/Multiverse-io/anonymiser/pull/163/files#diff-c7b6c38a3c3db9ad45d1ca13fc129931e4527 …
> Add truncate option

- README.md
- src/file_reader.rs
- src/fixers/db_mismatch.rs
- src/parsers/copy_row.rs
- src/parsers/row_parser.rs
- src/parsers/state.rs
- src/parsers/strategies.rs
- src/parsers/strategy_structs.rs
- src/parsers/transformer.rs
- src/test_builders.rs
This PR implements a global salt mechanism for the anonymisation process. The salt is specified in the strategy.json file and is applied consistently across all hashing operations.
- Added support for reading a global salt from strategy.json
- The salt configuration must be the first item in the strategy file array
- Modified the transformer logic to incorporate salt in hashing operations
- Updated tests to verify salt functionality
The strategy.json file should now follow this structure:
```json
[
{
"salt": "global-salt-here"
},
{
"table_name": "public.registrations",
"description": "",
"columns": [
// ... existing columns ...
]
},
// ... rest of the tables ...
]
```
- The salt configuration must be the first item in the array
- The salt is applied globally to all tables that require …
> Add salt to hashing logic

- README.md
- src/parsers/row_parser.rs
- src/parsers/strategies.rs
- src/parsers/transformer.rs
([SQD-67](https://linear.app/multiverse-io/issue/SQD-67/update-anonymiser-tool-to-hash-ids))
As part of the anonymisation work we should be anonymising some id's to make it harder to link back to our production data. This PR adds this functionality
```
CREATE TABLE public.users (
user_id SERIAL,
account_id VARCHAR(255),
customer_id VARCHAR(255),
user_uuid UUID,
first_name VARCHAR(255),
last_name VARCHAR(255),
full_name VARCHAR(255)
);
INSERT INTO public.users (user_id, account_id, customer_id, user_uuid, first_name, last_name, full_name) VALUES 
(1, 'ACC_001', 'CUST_001', '123e4567-e89b-12d3-a456-426614174000', 'John', 'Smith', 'John Smith'),
(2, 'ACC_001', 'CUST_002', '223e4567-e89b-12d3-a456-426614174001', 'John', 'Brown', 'John Brown'),
(3, 'ACC_002', 'CUST_001', …
```
> Update anonymiser tool to hash ID's

- README.md
- src/parsers/transformer.rs
The email anonymisation logic has been updated to use a more deterministic approach, Instead of using incrementing numbers or optional unique prefixes, we now use a hash-based prefix. The prefix is generated by hashing the original email and taking the first 6 bytes.
I'll update the Reef doc in a follow-up PR once I get approval on this.
> Update anonymiser FakeEmail logic

- README.md
- src/helpers.rs
- src/main.rs
- src/opts.rs
Adds two new CLI commands to help teams debug production issues locally by getting anonymised versions of production user IDs and emails
1. `cargo build`
2. Basic Email Anonymisation Testing
```
./target/debug/anonymiser anonymise-email --email "user@example.com"
./target/debug/anonymiser anonymise-email --email "user@example.com"
./target/debug/anonymiser anonymise-email --email "different@example.com"
```
3. ID Anonymisation Testing
```
./target/debug/anonymiser anonymise-id --id "user123" --transformer "FakeUUID" --args '{"deterministic": "true"}'
./target/debug/anonymiser anonymise-id --id "user123" --transformer "FakeUUID" --args '{"deterministic": "true"}' --salt "prod2024"
```
4.  documentation help: `./target/debug/anonymiser --help`
> Add helper functions
